tell application "Reminders"
    set mirrorList to list "Mirror"
    tell mirrorList
        make new reminder with properties {name:"🔴 Form New Mexico LLC (operating entity)", due date:date "March 28, 2026", body:"Form NM LLC for content platform. Does not require member disclosure. Use commercial registered agent. Blocks payment processing, AdSense, app store accounts, and all business banking. Priority #1 from BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🔴 Get EIN from IRS for LLC", due date:date "March 28, 2026", body:"Apply for Employer Identification Number online at IRS.gov. Use LLC registered agent address, not personal address. Required for bank accounts and Stripe."}
        make new reminder with properties {name:"🔴 Open business bank account in LLC name", due date:date "March 28, 2026", body:"Open account at Mercury or Relay (online-first, no in-person visit). Requires EIN and LLC documents. Never use personal card for business expenses. Per PRIVACY_ANONYMITY_PLAN."}
        make new reminder with properties {name:"🔴 Purchase all remaining domains", due date:date "March 25, 2026", body:"Purchase if not already owned: levnation.com, levciti.com, levlife.co, hisrequirements.com, herrequirements.com, xamory.com, xamlr.com. Register all with WHOIS privacy enabled. Consider Cloudflare Registrar for at-cost pricing. Per BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🔴 Enable WHOIS privacy on ALL domains", due date:date "March 25, 2026", body:"Verify WHOIS privacy is active on trueassess.me, truemirror.me, onelist.my, and all newly purchased domains. Run WHOIS lookups to confirm. Check WHOIS history for any past exposure via DomainTools. Per PRIVACY_ANONYMITY_PLAN Section 2.1."}
        make new reminder with properties {name:"🔴 Purchase 2x YubiKey 5C NFC hardware security keys", due date:date "March 25, 2026", body:"$50 each. Register both on all critical accounts (email, cloud, registrar, payment, bank). Store one on person, one in secure location. Phishing-proof 2FA. Per PERSONAL_SECURITY_PLAN Level 1."}
        make new reminder with properties {name:"🔴 Set up password manager (1Password or Bitwarden)", due date:date "March 25, 2026", body:"Generate unique random passwords for every business account. Master password: 5+ random words. Per PERSONAL_SECURITY_PLAN Level 1."}
        make new reminder with properties {name:"🔴 Set up VPN service for all business activity", due date:date "March 25, 2026", body:"Subscribe to Mullvad ($60/yr) or ProtonVPN ($48/yr). Use for ALL business-related internet activity. Masks IP from services. Per PERSONAL_SECURITY_PLAN and PRIVACY_ANONYMITY_PLAN."}
        make new reminder with properties {name:"🔴 Set up dedicated business email on ProtonMail", due date:date "March 25, 2026", body:"Create ProtonMail account with custom domain. Set up email aliases: info@, press@, legal@, admin@, support@. Enable 2FA with YubiKey. Never send business email from personal accounts. Per PRIVACY_ANONYMITY_PLAN Section 5.1."}
        make new reminder with properties {name:"🔴 Set up PO Box or UPS Store mailbox for business address", due date:date "March 28, 2026", body:"Get UPS Store mailbox (provides street address format) or USPS PO Box for all business correspondence. ~$200-400/year. Use on ALL business documents. Never use personal home address. Per PRIVACY_ANONYMITY_PLAN Section 3.4."}
        make new reminder with properties {name:"🟡 Set up business phone number (Google Voice or OpenPhone)", due date:date "March 28, 2026", body:"Separate number for all business contacts. Never give personal phone to any business contact. Per PRIVACY_ANONYMITY_PLAN Section 3.5."}
        make new reminder with properties {name:"🟡 Set up Google Workspace for business email ($7/mo)", due date:date "March 28, 2026", body:"Needed for Google Search Console verification, business communications. Use LLC entity details. Per CASH_NEEDS_SCHEDULE."}
        make new reminder with properties {name:"🟢 Subscribe to Canva Pro for design tools ($13/mo)", due date:date "March 28, 2026", body:"Needed for social media graphics, thumbnails, brand assets. Per CASH_NEEDS_SCHEDULE."}
        make new reminder with properties {name:"🔴 Purchase media liability insurance", due date:date "March 28, 2026", body:"Covers defamation, libel, invasion of privacy, copyright infringement. $1,000-3,000/year for $1M coverage. Providers: Hiscox, Hartford. Essential for publishing religious/political analysis. Per PERSONAL_SECURITY_PLAN Level 2 and CASH_NEEDS_SCHEDULE ($50/mo amortized)."}
        make new reminder with properties {name:"🔴 Register all domains with Cloudflare DNS", due date:date "March 28, 2026", body:"Point trueassess.me, truemirror.me, levnation.com, levciti.com, levlife.co, xamory.com, xamlr.com, onelist.my to Cloudflare. Free tier provides CDN, DDoS protection, SSL, DNS. Per CDN_INFRASTRUCTURE_PLAN and BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🔴 Set up registered agent service (annual)", due date:date "March 28, 2026", body:"Commercial registered agent for NM LLC (Northwest, Incfile, or ZenBusiness). $100-300/year. Accepts legal documents, provides address for public filings. Per PRIVACY_ANONYMITY_PLAN."}
        make new reminder with properties {name:"🟡 Conduct social media audit — remove personal info", due date:date "March 28, 2026", body:"Review all personal social media accounts. Remove info that connects personal identity to business. Set all to private. Remove location data. Google yourself: name, phone, email, address. Per PERSONAL_SECURITY_PLAN Level 1."}
        make new reminder with properties {name:"🟡 Submit data broker opt-out requests", due date:date "March 28, 2026", body:"Submit removal requests to Spokeo, WhitePages, BeenVerified, Intelius, PeopleFinder. Or subscribe to DeleteMe ($129/yr) to automate. Per PERSONAL_SECURITY_PLAN Level 1."}
        make new reminder with properties {name:"🔴 Verify Google Search Console for all domains (DNS TXT)", due date:date "April 1, 2026", body:"Register trueassess.me, truemirror.me, levnation.com, levciti.com as Domain properties in GSC. Add DNS TXT verification records. Submit sitemaps. Request indexing for key pages. Per SEARCH_AI_INDEXING_PLAN Section 1.1."}
        make new reminder with properties {name:"🟡 Set up Bing Webmaster Tools (import from GSC)", due date:date "April 1, 2026", body:"Import all properties from Google Search Console. Bing powers Bing, Yahoo, DuckDuckGo, and Microsoft Copilot. Per SEARCH_AI_INDEXING_PLAN Section 1.2."}
        make new reminder with properties {name:"🟡 Generate and deploy IndexNow API keys for all domains", due date:date "April 1, 2026", body:"Generate UUID key, save as text file at each domain root. Integrate into deployment pipeline so every page create/update fires an IndexNow ping. Works for Bing and Yandex. Per SEARCH_AI_INDEXING_PLAN."}
        make new reminder with properties {name:"🟡 Configure robots.txt for all domains — allow AI crawlers", due date:date "April 1, 2026", body:"Allow GPTBot, OAI-SearchBot, ClaudeBot, anthropic-ai, PerplexityBot in robots.txt on all domains. AI systems are a primary discovery channel (30-40% of queries). Per SEARCH_AI_INDEXING_PLAN Section 2."}
        make new reminder with properties {name:"🟢 Create llms.txt files for all domains", due date:date "April 4, 2026", body:"Create llms.txt (analogous to robots.txt but for AI) on each domain describing site purpose, content structure, and key pages. Per SEARCH_AI_INDEXING_PLAN."}
        make new reminder with properties {name:"🟡 Deploy Schema.org JSON-LD markup across all sites", due date:date "April 4, 2026", body:"Organization, Product, FAQPage, HowTo, Article, NewsArticle (levnation), DiscussionForumPosting schemas. Per SEARCH_AI_INDEXING_PLAN Section 3."}
        make new reminder with properties {name:"🔴 Publish Wave 1 foundation content — 20 cornerstone pages", due date:date "April 4, 2026", body:"Deploy first 20 CttC pages on trueassess.me: attachment styles (all 4), enneagram (overview + 9 types), Big Five, narcissism spectrum, love languages, communication styles, cognitive distortions, emotional intelligence, trauma responses, shadow work. 2,000-4,000 words each, research-cited. No product CTAs yet. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.2."}
        make new reminder with properties {name:"🔴 Set up ConvertKit (Kit) email infrastructure", due date:date "April 1, 2026", body:"Create account, set up custom sending domain (mail.trueassess.me), configure DKIM/SPF/DMARC records, build welcome automation, set up double opt-in. Test deliverability (target 9+/10 on mail-tester.com). Per WEEK_MINUS_8_BUZZ_PLAN Section 2.3."}
        make new reminder with properties {name:"🔴 Set up Stripe account under LLC", due date:date "April 1, 2026", body:"Register with LLC EIN, business address, business email. Configure three Founding Member products: $39/yr annual, $299 lifetime, $499 all-access lifetime. Set up Stripe Tax for auto sales tax. Test purchase flow end-to-end. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.5."}
        make new reminder with properties {name:"🟢 Set up Plausible Analytics (privacy-respecting)", due date:date "April 4, 2026", body:"Self-hosted or cloud ($9/mo at scale). Privacy-respecting, no cookie banner needed for analytics alone. Deploy on all domains. Per WEEKLY_FINANCIAL_FORECAST and CDN_INFRASTRUCTURE_PLAN."}
        make new reminder with properties {name:"🔴 Publish Wave 1 expansion content — 30 more pages", due date:date "April 11, 2026", body:"Comparison pages (MBTI vs Enneagram vs Big Five), \"Am I...\" pages (narcissist, codependent, emotionally unavailable), relationship impact pages, belief decomposition preview pages. Build internal link structure. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.2."}
        make new reminder with properties {name:"🔴 Create all social media accounts — let accounts age", due date:date "April 5, 2026", body:"Create and brand accounts on X/Twitter (@trueassess + @truemirror), Bluesky (@trueassess.me + @truemirror.me), Reddit (u/trueassess_research), Discord server, Instagram (@trueassess), TikTok (@trueassess), YouTube (trueassess.me). Accounts need aging to avoid spam filters. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.4."}
        make new reminder with properties {name:"🟡 Set up Discord server with channels", due date:date "April 5, 2026", body:"Create trueassess.me Self-Knowledge Community server. Channels: #welcome, #announcements, #attachment-styles, #enneagram, #personality-types, #relationship-patterns, #belief-decomposition, #founding-members (locked/visible), #ask-mirror, #feedback. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.3."}
        make new reminder with properties {name:"🟡 Begin Reddit karma building (u/trueassess_research)", due date:date "April 5, 2026", body:"Post genuine value in r/psychology, r/selfimprovement, r/attachment_theory. No links, just good answers. Target 500+ karma before Week -8 announcement. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.2."}
        make new reminder with properties {name:"🟡 Consider multi-entity LLC structure (ADL/deplatforming risk)", due date:date "April 11, 2026", body:"PRIVACY_ANONYMITY_PLAN recommends separate LLCs: Content LLC (truemirror/trueassess/levnation), Assessment LLC (xamory), Infrastructure LLC (onelist). Prevents financial deplatforming of one product from killing all. Additional cost: $800-3,100/year. Decision needed."}
        make new reminder with properties {name:"🔴 Publish Wave 1 final — 20 assessment-adjacent pages", due date:date "April 18, 2026", body:"Landing pages for top 10 assessment types. \"Why Every Personality Test You've Taken Was Gameable\" (anti-gaming manifesto). \"The Belief Decomposition Engine: How trueassess.me Works.\" \"What Would Happen If You Took 20 Personality Tests at Once?\" Per WEEK_MINUS_8_BUZZ_PLAN."}
        make new reminder with properties {name:"🟡 Send academic advisory board outreach emails", due date:date "April 12, 2026", body:"Identify and email 5-10 academics in psychometrics, personality psychology, relationship science. They endorse methodology, not product. Need 3-5 confirmed by Week 5. Listed on About page with university affiliations. Per ASTEROID_LAUNCH_STRATEGY Section 1.3."}
        make new reminder with properties {name:"🟡 Pre-register 2-3 validation studies on OSF", due date:date "April 18, 2026", body:"Register on Open Science Framework (osf.io): (1) Convergent Validity study, (2) Anti-Gaming Effectiveness study, (3) Belief Decomposition and Self-Knowledge study. Pre-registration signals scientific rigor. Per ASTEROID_LAUNCH_STRATEGY Section 1.3."}
        make new reminder with properties {name:"🟡 Begin Mirror bot voice calibration and testing", due date:date "April 18, 2026", body:"Post 20 test threads, evaluate voice consistency. Reply to 50 simulated conversations. Stress-test against adversarial inputs. Verify no content reveals founder identity. Test scheduling and cross-platform posting. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.6."}
        make new reminder with properties {name:"🟢 Set up Sentry for error tracking", due date:date "April 18, 2026", body:"Deploy Sentry across all domains for error tracking. Part of monitoring stack alongside UptimeRobot. Per ASTEROID_LAUNCH_STRATEGY infrastructure checklist."}
        make new reminder with properties {name:"🔴 Deploy trueassess.me waitlist/teaser landing page", due date:date "April 19, 2026", body:"Above fold: headline + email capture + Founding Member pitch. Below fold: 3 proof points + ecosystem tease + FAQ + second email capture. Countdown timer for FM spots. Fast (<2s load), mobile-optimized, OG/Twitter cards, Schema.org markup. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.1."}
        make new reminder with properties {name:"🟡 Deploy satellite \"coming soon\" pages for all ecosystem domains", due date:date "April 19, 2026", body:"Minimal page on each: truemirror.me, xamory.com, xamlr.com, levnation.com, levciti.com, levlife.co. Logo + name + one-sentence description + \"Coming soon\" + email capture + link back to trueassess.me. Per WEEK_MINUS_8_BUZZ_PLAN."}
        make new reminder with properties {name:"🟢 Begin podcast pitching for Mirror/trueassess", due date:date "April 19, 2026", body:"Pitch 20-30 podcasts in relationship/psychology/self-improvement space. Angle: anonymous founder, AI as guest. Target smaller shows (10K-50K listeners): Therapy for Black Girls, Psychology in Seattle, Love Is Like a Plant, Deeper Dating. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.8."}
        make new reminder with properties {name:"🟢 Sign up for HARO/Connectively, Source of Sources, Qwoted", due date:date "April 25, 2026", body:"Respond to journalist queries about personality testing, relationships, dating psychology. When quoted, get backlink. Free. 15 min/response. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.8."}
        make new reminder with properties {name:"🟡 Create Product Hunt \"upcoming\" page for trueassess.me", due date:date "April 25, 2026", body:"Start collecting followers on PH upcoming page. Link in emails and social bios. Engage in PH community. Goal: 200+ followers by D-Day. DO NOT launch on PH now — save for D-Day. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.6."}
        make new reminder with properties {name:"🟢 Create Substack newsletter as distribution channel", due date:date "April 25, 2026", body:"\"Decomposed by trueassess.me\" — weekly post mirroring email content. Substack recommendation network surfaces to similar subscribers. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.8."}
        make new reminder with properties {name:"🟢 Cross-post blog content to Medium", due date:date "April 25, 2026", body:"2-3 posts/week from trueassess.me blog to Medium. Tags: Psychology, Self Improvement, Personality, Relationships, Data Science. Medium's algo can surface to relevant audiences. Per WEEK_MINUS_8_BUZZ_PLAN."}
        make new reminder with properties {name:"🔴 Mirror bot value-building phase begins on X + Bluesky", due date:date "April 26, 2026", body:"Mirror posts 3-4 threads/day on X and Bluesky. PURE VALUE — no mention of trueassess.me yet. Attachment styles, relationship patterns, belief decomposition concepts. Target: 500-2,000 followers by Week -8 announcement. Per WEEK_MINUS_8_BUZZ_PLAN Phase 1."}
        make new reminder with properties {name:"🟡 Begin TikTok/Instagram Reels content production", due date:date "April 26, 2026", body:"1 video/day, 7 days/week. \"The Decomposition\" series — decompose personality labels live. AI voiceover (ElevenLabs), text overlays, 15-60 seconds. Cross-post to TikTok, Instagram Reels, YouTube Shorts. $0 production cost. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.4."}
        make new reminder with properties {name:"🟡 Begin YouTube long-form content production", due date:date "April 26, 2026", body:"2 long-form videos/week + daily Shorts. First: \"Why Every Personality Test Is Broken\" (12-15 min) and \"Your Attachment Style Is 12 Beliefs\" (10-12 min). No face needed — animated slides, screen recordings, AI voiceover. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.5."}
        make new reminder with properties {name:"🔴 Deploy 200+ static content pages across all sites", due date:date "May 2, 2026", body:"Per ASTEROID_LAUNCH_STRATEGY Week -12 checklist: 50 assessment landing pages (trueassess), 50 belief decomposition pages, 30 pattern encyclopedia pages (truemirror), 30 controversy pages (levnation), 10 city pages (levciti), 30 CttC pages. Full 2,000-5,000 word pages with schema markup."}
        make new reminder with properties {name:"🟡 Send micro-influencer outreach DMs (30 creators)", due date:date "April 26, 2026", body:"Identify 30 psychology/relationship/self-improvement creators on TikTok/Instagram (10K-100K followers). Offer free premium accounts with early access. Ask them to take assessments and share reactions honestly. Per ASTEROID_LAUNCH_STRATEGY Section 1.1 Phase 3."}
        make new reminder with properties {name:"🟡 Send therapist/coach outreach (200 emails)", due date:date "May 2, 2026", body:"Offer 200 free professional accounts. Each therapist assigning assessments to 3-5 clients generates 600-1,000 accounts. These users provide highest-quality feedback. Per ASTEROID_LAUNCH_STRATEGY Track 4."}
        make new reminder with properties {name:"🟢 Identify 20 target journalists and begin engagement", due date:date "April 26, 2026", body:"Target outlets: TechCrunch, The Verge, Psychology Today, NYT Well, The Atlantic, Vox. Follow, engage with, respond to their work on social media. Not pitching yet — building relationship. Per ASTEROID_LAUNCH_STRATEGY Phase 4."}
        make new reminder with properties {name:"🔴 X API Basic tier subscription ($100/mo)", due date:date "May 3, 2026", body:"Subscribe to X API Basic tier for Mirror bot. Provides 10K reads/mo, 3K writes/mo, DM access. Enough for launch phase. Upgrade to Pro ($5K/mo) only when daily reply volume exceeds 80. Per X_BOT_STRATEGY Section 2."}
        make new reminder with properties {name:"🔴 Deploy Mirror social bot on X + Bluesky + Discord", due date:date "May 3, 2026", body:"Bot goes live as interactive social presence. Mention Poller, DM Poller, Search Scanner, Context Parser, Knowledge Base Query, LLM Response Generator, Content Gate, Thread Builder. Label as automated account in bio. Per MIRROR_SOCIAL_PRESENCE and X_BOT_STRATEGY."}
        make new reminder with properties {name:"🟡 Set up Discord bot integration for Mirror", due date:date "May 3, 2026", body:"Mirror bot as Discord bot. Slash commands: /mirror pattern, /mirror explain, /mirror framework. Rich embeds with buttons. Free API (no Discord fees). Per MIRROR_SOCIAL_PRESENCE Section 3.2."}
        make new reminder with properties {name:"🟡 Configure Bluesky bot account (@truemirror.me)", due date:date "May 3, 2026", body:"Bluesky allows domain handles for verification. Use AT Protocol for bot interaction. Free API. Currently favors small accounts with good content. Per MIRROR_SOCIAL_PRESENCE Section 3.4."}
        make new reminder with properties {name:"🔴 Wave 2 content expansion — 150 pages deployed", due date:date "May 16, 2026", body:"Belief decomposition pages (showcase), presupposition pages, relationship impact pages. NOW include product CTAs: \"Take the free assessment at trueassess.me\" and \"Join as a Founding Member.\" Per WEEK_MINUS_8_BUZZ_PLAN Section 5.1."}
        make new reminder with properties {name:"🔴 Build 8-week email nurture sequence in ConvertKit", due date:date "May 16, 2026", body:"Triggered on waitlist signup. Each email in the sequential reveal sequence aligns with the weekly product reveals. Tags per source. Discord invite link in every email. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.3."}
        make new reminder with properties {name:"🔴 Set up Founding Member counter on teaser page", due date:date "May 16, 2026", body:"Real-time counter via Stripe webhook: \"Founding Member spots remaining: [X]/1,000\". When 0, offer disappears. Creates genuine scarcity. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.5."}
        make new reminder with properties {name:"🔴 Deploy limited trueassess.me beta with 5 free assessments", due date:date "May 16, 2026", body:"Attachment style, Big Five, Enneagram, communication style, conflict resolution. No login to start, login to save. Every result page has shareable card (Instagram Stories 9:16). \"Challenge a friend\" button. Per ASTEROID_LAUNCH_STRATEGY Track 1."}
        make new reminder with properties {name:"🔴 Draft and publish privacy policy for all domains", due date:date "May 16, 2026", body:"GDPR and CCPA compliant. Covers cookies, ad personalization, data collection, user rights. Required for AdSense approval. Host at /privacy on each domain. Per AD_REVENUE_LAUNCH_PLAN and BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🔴 Draft and publish Terms of Service for all domains", due date:date "May 16, 2026", body:"User conduct, intellectual property (belief decomposition content is proprietary), disclaimer, limitation of liability. Host at /terms on each domain. Per AD_REVENUE_LAUNCH_PLAN and BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🔴 Deploy cookie consent banner (CMP) on all domains", due date:date "May 16, 2026", body:"GDPR-required. Must integrate with Google TCF 2.0 framework. Granular consent — users can opt out of personalized ads. Options: Cookiebot ($0-12/mo), OneTrust (free tier), Quantcast Choice (free). Per AD_REVENUE_LAUNCH_PLAN Section 1.1."}
        make new reminder with properties {name:"🔴 Execute Mirror bot announcement thread on X + Bluesky", due date:date "May 17, 2026", body:"Mirror reveals it's built on trueassess.me. 6-tweet thread with logo image. Announces 1,000 Founding Member spots. Previews the 8-week ecosystem reveal. Per WEEK_MINUS_8_BUZZ_PLAN Phase 2."}
        make new reminder with properties {name:"🔴 Launch Discord server publicly", due date:date "May 17, 2026", body:"Post Discord link in announcement thread. Pin welcome message. Mirror bot posts daily insights. #founding-members channel visible but locked for FOMO. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.3."}
        make new reminder with properties {name:"🔴 Post announcement on Reddit (4 target subreddits)", due date:date "May 17, 2026", body:"r/selfimprovement (2.4M), r/psychology (1.2M), r/attachment_theory (50K), r/mbti (700K+). Value-first posts, 800+ words. Stay in threads answering questions. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.2."}
        make new reminder with properties {name:"🟡 Post Show HN on Hacker News", due date:date "May 17, 2026", body:"\"Show HN: A psychometric engine that decomposes personality labels into belief bundles.\" Technical angle. If waitlist disqualifies for Show HN, post as blog article link instead. Per WEEK_MINUS_8_BUZZ_PLAN Section 4.7."}
        make new reminder with properties {name:"🟡 Begin paid ad spend ($190/week for 8 weeks)", due date:date "May 17, 2026", body:"$1,500 total budget. Platforms: Google, Reddit, Meta, TikTok. Target high-intent keywords: \"accurate personality test,\" \"attachment style test.\" Per WEEKLY_FINANCIAL_FORECAST and WEEK_MINUS_8_BUZZ_PLAN Section 6."}
        make new reminder with properties {name:"🔴 Send Email 1 — Founding Member announcement", due date:date "May 17, 2026", body:"First email of 8-week nurture sequence to entire waitlist. Announces trueassess.me, opens Founding Member sales. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🟡 Send Email 2 — sustained social proof", due date:date "May 24, 2026", body:"Second nurture email. Include FM count update, early testimonials if available, ecosystem tease. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🟡 Send personalized press kit to 20 journalists (Week -4)", due date:date "May 24, 2026", body:"One-line pitch + early access. \"We built an assessment engine that decomposes every personality type into its constituent beliefs. 210 frameworks. Anti-gaming. Five-property ecosystem. Embargo lifts [July 12].\" Per ASTEROID_LAUNCH_STRATEGY Phase 4."}
        make new reminder with properties {name:"🔴 truemirror.me teased — Email 3", due date:date "May 31, 2026", body:"Reveal truemirror.me: AI relationship coaching. \"Coming soon — included for Founding Members.\" Update satellite page with more detail. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🟡 Knowledge base reveal — Email 4", due date:date "June 7, 2026", body:"Reveal the depth of the CttC knowledge base. Show examples of belief decomposition, presupposition excavation, evidence synthesis. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🔴 Wave 3 content deployment — 300+ pages, ~1M words", due date:date "June 13, 2026", body:"Remaining belief pages, compatibility pages, type-combination pages. Programmatic SEO for type combinations. Maximum SEO surface area before launch. Per WEEK_MINUS_8_BUZZ_PLAN Section 5.1."}
        make new reminder with properties {name:"🔴 xamory.com + xamlr.com teased — Email 5", due date:date "June 14, 2026", body:"Dating + blogging as one ecosystem. \"Coming soon — included for Founding Members.\" Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🔴 Apply for Google AdSense (Week -3 from launch)", due date:date "June 14, 2026", body:"Apply for levnation.com AND levciti.com separately. Need 20-30 original pages, privacy policy, ToS, about page, contact page, cookie consent. Approval takes 1-14 days, political content may flag for manual review (3-7 extra days). Per AD_REVENUE_LAUNCH_PLAN Section 1.1."}
        make new reminder with properties {name:"🟡 Apply for Ezoic (backup ad network)", due date:date "June 14, 2026", body:"Apply simultaneously with AdSense. No traffic minimum. Approval 2-5 days. If AdSense not approved by launch, launch with Ezoic. Per AD_REVENUE_LAUNCH_PLAN."}
        make new reminder with properties {name:"🟡 Apply for Google political ad certification", due date:date "June 14, 2026", body:"levnation.com needs certification for political ad inventory (CPMs $15-40, 3-8x typical display). US-based entity, FEC compliance. Approval 5-10 business days. Per AD_REVENUE_LAUNCH_PLAN Section 1.2."}
        make new reminder with properties {name:"🟡 Submit Google News Publisher Center application for levnation.com", due date:date "June 14, 2026", body:"Publication name, URL, description, category. Google reviews in 2-4 weeks. Requires substantial original content, author bylines, publication dates, About page, NewsArticle schema. Per SEARCH_AI_INDEXING_PLAN Section 1.1."}
        make new reminder with properties {name:"🔴 Deploy content for ad network approval (50 controversy + 10 city pages)", due date:date "June 14, 2026", body:"Minimum for AdSense approval: 50 controversy/belief decomposition pages on levnation.com, 10 city pages on levciti.com. 500+ words each, original content, internal linking. Per AD_REVENUE_LAUNCH_PLAN Section 1.3."}
        make new reminder with properties {name:"🟡 Belief decomposition reveal — Email 6", due date:date "June 21, 2026", body:"Deep dive into how belief decomposition works. The core differentiator. Show presupposition excavation, evidence confrontation. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🟡 Design and test ad placement layouts (Week -2 from launch)", due date:date "June 21, 2026", body:"Max 3 ad units per page. Sidebar sticky, in-content between sections, below-content. Never interrupt decomposition flow. Never above fold on mobile. Ad-to-content ratio min 70/30. No interstitials, pop-ups, or autoplay. Per AD_REVENUE_LAUNCH_PLAN Section 1.4-1.5."}
        make new reminder with properties {name:"🟡 Configure ad category blocking rules", due date:date "June 21, 2026", body:"Block: competing quiz products, predatory finance, weight loss pills, gambling, deceptive formats. levnation-specific: allow political ads (high CPM) but block single-issue advocacy that looks editorial. levciti-specific: block national political ads, MLM. Per AD_REVENUE_LAUNCH_PLAN Section 1.6."}
        make new reminder with properties {name:"🔴 Ensure all 210+ assessments are functional", due date:date "June 27, 2026", body:"Core differentiator. Anti-gaming engine deployed and tested. Belief decomposition engine running for all assessments. Presupposition excavation pages live for top 50 beliefs. Per ASTEROID_LAUNCH_STRATEGY product completion checklist."}
        make new reminder with properties {name:"🔴 Complete compatibility engine (pairwise + group)", due date:date "June 27, 2026", body:"Both pairwise and 3+ person group compatibility must be functional. Every compatibility request is a user acquisition event. Per ASTEROID_LAUNCH_STRATEGY product completion."}
        make new reminder with properties {name:"🔴 Complete Mirror conversation import + pattern detection", due date:date "June 27, 2026", body:"iMessage export, WhatsApp export, manual paste all functional. Pattern detection running on imported conversations. Game film review feature functional. Per ASTEROID_LAUNCH_STRATEGY product completion."}
        make new reminder with properties {name:"🔴 Complete OneList cross-domain authentication", due date:date "June 27, 2026", body:"Single sign-on working seamlessly across all five domains. OAuth flow tested. One email, all products. Per ASTEROID_LAUNCH_STRATEGY and project_simultaneous_launch."}
        make new reminder with properties {name:"🔴 Complete subscription and payment processing", due date:date "June 27, 2026", body:"Stripe live. Free tier properly gated (5 assessments, no belief decomposition, no compatibility). Individual ($9/mo), Couple ($14/mo), Business ($29/seat/mo) tiers properly gated. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Retain lawyer for internet law / anti-SLAPP", due date:date "June 21, 2026", body:"Initial consultation $200-500. Retainer $2,000-5,000/year. Must be experienced in internet law, First Amendment, anti-SLAPP. Choose state with strong anti-SLAPP (CA, OR, WA, TX, NV). Budget $10K-50K for defending a single SLAPP suit. Per PERSONAL_SECURITY_PLAN Level 2."}
        make new reminder with properties {name:"🔴 levnation.com + levciti.com teased — Email 7", due date:date "June 28, 2026", body:"Civic engagement layer revealed. Full ecosystem scope now visible. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🟡 Install GA4 + ad revenue tracking", due date:date "June 28, 2026", body:"Google Analytics 4 on both ad domains. Page-level tracking, ad event tracking, audience segments, conversion tracking, cross-domain tracking (levnation → trueassess.me). Per AD_REVENUE_LAUNCH_PLAN Section 1.7."}
        make new reminder with properties {name:"🟡 Set up ad tech implementation — lazy loading, async, pre-sizing", due date:date "June 28, 2026", body:"Lazy load below-fold ads. All ad scripts async. Pre-size ad slots to prevent CLS. Google Publisher Tag async. Target: <3s load on 3G mobile with ads. Per AD_REVENUE_LAUNCH_PLAN Section 1.8."}
        make new reminder with properties {name:"🟢 Build daily revenue dashboard", due date:date "June 28, 2026", body:"Track daily revenue, pageviews, effective CPM, top revenue pages, viewability, CTR. Google Sheet pulling from AdSense API, or Databox/Geckoboard. Per AD_REVENUE_LAUNCH_PLAN Section 1.7."}
        make new reminder with properties {name:"🔴 Run load testing at 10x expected traffic", due date:date "July 4, 2026", body:"HARD GATE FOR LAUNCH. Two consecutive clean passes required. Test: static content, OneList API, assessment engine, Mirror WebSocket, database queries, ad serving, cross-site API calls. Tools: k6, Artillery, Lighthouse CI, Playwright. P99 <500ms static, <2s dynamic. Zero errors at 10x. Per project_load_testing."}
        make new reminder with properties {name:"🔴 Document rollback plan", due date:date "July 4, 2026", body:"If something breaks, revert in <5 minutes. Document the exact steps. Per ASTEROID_LAUNCH_STRATEGY launch logistics."}
        make new reminder with properties {name:"🟡 Finalize Product Hunt listings", due date:date "July 4, 2026", body:"Listings for trueassess.me, truemirror.me (Mirror), levnation.com. Recruit 5-10 respected PH members as early testers. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Draft Hacker News posts (3 angles)", due date:date "July 4, 2026", body:"(1) Technical anti-gaming angle, (2) Belief decomposition angle, (3) Ecosystem concept. Only post one on D-Day. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Draft Reddit launch posts for 10+ subreddits", due date:date "July 4, 2026", body:"Genuine value-add format. Subreddits: r/mbti, r/enneagram, r/psychology, r/selfimprovement, r/relationships, r/attachment_theory, r/ADHD, r/dataisbeautiful. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Queue 30+ social media pieces for launch day/week", due date:date "July 4, 2026", body:"TikTok, Instagram Reels, X threads, YouTube videos all pre-produced and scheduled. Per ASTEROID_LAUNCH_STRATEGY launch logistics."}
        make new reminder with properties {name:"🔴 Draft and test email blast to entire waitlist", due date:date "July 4, 2026", body:"\"Your full profile is ready. 209 more assessments just unlocked.\" Personalized to beta results. CTA: log in + invite for compatibility. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Confirm influencer content for launch week publication", due date:date "July 4, 2026", body:"15+ micro-influencer posts coordinated for launch day. 3-5 mid-tier creator videos confirmed. All with unique tracking links. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Complete press embargo briefings", due date:date "July 4, 2026", body:"Journalists have had 2+ weeks with product. Press release finalized. Embargo lift: 06:00 ET on July 12. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Send full press kit to journalists", due date:date "July 4, 2026", body:"Press release, founder bio (anonymous angle), product screenshots, competitive positioning, beta data points, key differentiators. Embargo until July 12. Per ASTEROID_LAUNCH_STRATEGY Phase 4."}
        make new reminder with properties {name:"🟡 Install home security system", due date:date "July 4, 2026", body:"Exterior cameras (all entry points, driveway), motion-activated lighting, door/window sensors, monitored alarm. Ring, SimpliSafe, or professional install. $300-1,000 equipment + $15-50/mo monitoring. Per PERSONAL_SECURITY_PLAN Level 3."}
        make new reminder with properties {name:"🟢 Reinforce entry points at residence", due date:date "July 4, 2026", body:"Replace exterior door frames with reinforced steel frames. Install 3-inch screws in strike plates ($10 upgrade). Add deadbolts. Consider security film on ground-floor windows. $500-2,000. Per PERSONAL_SECURITY_PLAN Level 3."}
        make new reminder with properties {name:"🟡 Visit local police precinct — introduce yourself", due date:date "July 4, 2026", body:"Explain platform may attract threats from organized groups. Provide contact info. Ask to be flagged in system for swatting prevention. 30 minutes, free. Can prevent armed SWAT response to false report. Per PERSONAL_SECURITY_PLAN Level 3."}
        make new reminder with properties {name:"🟢 Prepare go-bag for emergencies", due date:date "July 4, 2026", body:"Essential documents (passport, ID copies, insurance cards), emergency cash, prepaid phone, basic supplies, change of clothes. Same preparedness as FEMA disaster kit. Per PERSONAL_SECURITY_PLAN Level 3."}
        make new reminder with properties {name:"🟡 Create emergency communication plan with family", due date:date "July 4, 2026", body:"Code word for danger, pre-identified meeting points, contact info for security firm and lawyer stored in multiple locations. Per PERSONAL_SECURITY_PLAN Level 3."}
        make new reminder with properties {name:"🔴 levlife.co teased + final push — Email 8", due date:date "July 5, 2026", body:"The complete picture revealed. \"levlife.co — the full ecosystem for living examined.\" Final urgency for Founding Members. Per project_sequential_reveal_launch."}
        make new reminder with properties {name:"🔴 Replace all \"coming soon\" pages with full sites in staging", due date:date "July 11, 2026", body:"All five domains ready for DNS cutover. trueassess.me, truemirror.me, levnation.com, levciti.com, onelist.my. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Pre-warm Cloudflare cache for top 1,000 pages", due date:date "July 11, 2026", body:"Before DNS cutover, ensure top pages are cached at all Cloudflare edge locations. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Verify ad rendering on all browsers/devices", due date:date "July 11, 2026", body:"Desktop Chrome/Firefox/Safari/Edge, Mobile iOS Safari, Mobile Android Chrome, Tablet. Verify no ads on conversion pages, cookie consent working, Core Web Vitals passing with ads (LCP <2.5s, FID <100ms, CLS <0.1). Per AD_REVENUE_LAUNCH_PLAN Section 2.1."}
        make new reminder with properties {name:"🔴 Final payment processing test", due date:date "July 11, 2026", body:"Real $1 test charge and refund. Verify purchase flow, webhook updates, email confirmations, FM counter decrement. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🔴 Verify cross-domain authentication across all sites", due date:date "July 11, 2026", body:"Create account on trueassess.me, verify SSO works on truemirror.me, levnation.com, levciti.com, levlife.co. OneList identity must be seamless. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🔴 Mobile experience testing on 10+ devices", due date:date "July 11, 2026", body:"Assessment question UI (large tap targets, swipe navigation), result card sharing on Instagram/TikTok/WhatsApp, compatibility engine, Mirror coaching interface. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🔴 Execute D-Day launch sequence (hour by hour)", due date:date "July 12, 2026", body:"00:00 DNS cutover. 05:00 systems check. 06:00 press embargo lifts + release distributed. 07:00 Product Hunt launches. 08:00 HN post. 09:00 social blitz all platforms. 10:00 email blast to waitlist. 11:00 influencer posts drop. 12:00 Reddit engagement. 13:00 YouTube premieres. Monitor all day. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Final ad push — $150 launch day spend", due date:date "July 12, 2026", body:"Last of the $1,500 ad budget. Concentrated push across Google, Reddit, Meta. Per CASH_NEEDS_SCHEDULE."}
        make new reminder with properties {name:"🟡 Implement header bidding (Prebid.js) — Week 2-3 post-launch", due date:date "July 26, 2026", body:"Increases revenue 20-40% over AdSense alone. Demand partners: Google AdX, Amazon TAM, Index Exchange, OpenX, Magnite, Xandr. Single largest revenue optimization. Per AD_REVENUE_LAUNCH_PLAN Section 1.8."}
        make new reminder with properties {name:"🟡 Apply for Apple Developer Account ($99/year)", due date:date "July 19, 2026", body:"Required for iOS app and Apple News. Per BRYAN_TASK_LIST. Start immediately post-launch for app development timeline."}
        make new reminder with properties {name:"🟡 Set up Google Play Console ($25 one-time)", due date:date "July 19, 2026", body:"Required for Android app submission. Per BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🟡 Deploy Spanish + Portuguese translations (Day 30)", due date:date "August 11, 2026", body:"AI translation pipeline (Claude/GPT-4 initial, native-speaker psychometric review for assessment questions). 600M+ native speakers. Per ASTEROID_LAUNCH_STRATEGY Section 1.5."}
        make new reminder with properties {name:"🟢 Deploy French, German, Hindi translations (Day 60)", due date:date "September 10, 2026", body:"Adds Western Europe and Indian subcontinent. Combined with English/Spanish/Portuguese covers ~3 billion people. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 File trademark for trueassess.me and ecosystem brands", due date:date "September 2026", body:"$350 filing fee. File after 3 months post-launch. Per CASH_NEEDS_SCHEDULE (Jun month 3 post-launch is ~Oct, but filing can begin earlier)."}
        make new reminder with properties {name:"🟡 Begin legal retainer (~$100-500/month)", due date:date "September 2026", body:"Per CASH_NEEDS_SCHEDULE. Retained attorney for internet law, anti-SLAPP, ongoing legal needs."}
        make new reminder with properties {name:"🟢 Establish SOC 2 Type I certification process", due date:date "October 2026", body:"Start SOC 2 prep. Takes 3-6 months for Type I. \"In progress\" status is better than nothing for enterprise buyers. Type II (6-12 months of audited ops) is 12-month target. Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
        make new reminder with properties {name:"🟢 Deploy Mandarin, Japanese, Korean, Arabic translations (Day 90)", due date:date "October 10, 2026", body:"CJK requires different UI. Arabic requires RTL layout. Adds ~2 billion speakers. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟢 Submit first academic paper (Month 6)", due date:date "January 2027", body:"\"A Multi-Axis Psychometric Engine with Structural Anti-Gaming: Design and Initial Validation.\" Target: Journal of Personality Assessment or Assessment. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Hire professional OSINT investigator for self-audit", due date:date "June 28, 2026", body:"Before launch. $500-2,000. Reveals what a motivated adversary could find about your identity. Better to know now. Per PERSONAL_SECURITY_PLAN Level 2."}
        make new reminder with properties {name:"🔴 Register with NCMEC as Electronic Service Provider", due date:date "June 28, 2026", body:"MUST happen before platform accepts user-uploaded content. Provide company legal name, EIN, designated CSAM response officer (24/7 available), technical contact, legal contact. Receive CyberTipline API credentials. Test integration. Per CSAM.md Part 1C Step 1."}
        make new reminder with properties {name:"🔴 Apply for PhotoDNA license from Microsoft", due date:date "June 14, 2026", body:"Free for qualifying platforms. Demonstrate you're an ESP with UGC. Sign licensing agreement. Receive API credentials. Combined with NCMEC hash list for known CSAM detection. 1 in 50 billion false positive rate. Per CSAM.md Part 2A."}
        make new reminder with properties {name:"🔴 Deploy PDQ hash-based scanning (interim before PhotoDNA)", due date:date "June 28, 2026", body:"Meta's open-source perceptual hashing. Deploy immediately while waiting for PhotoDNA approval. github.com/facebook/ThreatExchange. Run both in parallel once PhotoDNA is approved. Per CSAM.md Part 2A."}
        make new reminder with properties {name:"🔴 Apply for Thorn's Safer service", due date:date "June 14, 2026", body:"Cloud-based CSAM detection designed for smaller platforms. Single integration for multiple hash databases + AI classifier. Compliance support for NCMEC reporting. REST API. Days-to-weeks integration. Contact safer.io. Per CSAM.md Part 2A."}
        make new reminder with properties {name:"🔴 Implement mandatory reporting procedures", due date:date "June 28, 2026", body:"Any employee discovering CSAM → report to CSAM response officer immediately. Officer has authority to block content and disable accounts. CyberTipline reports filed within 24 hours. Document everything with timestamps. Per CSAM.md Part 1C Step 2."}
        make new reminder with properties {name:"🔴 Implement evidence preservation system", due date:date "June 28, 2026", body:"Preserve original files (binary-identical), metadata (IP, headers, user agent), account info, associated content, server logs. Encrypted at rest, access-controlled, audit logging. 90-day minimum retention, extendable to 180. Per CSAM.md Part 1C Step 3."}
        make new reminder with properties {name:"🔴 Designate CSAM Response Officer + Backup", due date:date "June 28, 2026", body:"Senior person with authority to block content and disable accounts, responsible for CyberTipline filings. Available 24/7. Backup for vacations/illness. Even if solo, document the designation formally. Per CSAM.md Part 1C Step 6."}
        make new reminder with properties {name:"🔴 Complete CSAM awareness training (even if solo founder)", due date:date "June 28, 2026", body:"What CSAM is, legal obligations, how to report internally, what NOT to do (don't view, don't share). Document training (who, when, what). Annual refresher. Critical compliance documentation. Per CSAM.md Part 1C Step 5."}
        make new reminder with properties {name:"🔴 Publish Child Safety Policy (public-facing)", due date:date "June 28, 2026", body:"Separate from ToS. Explains detection measures, how to report suspected CSAM, cooperation with NCMEC/LE, age verification. Reporting mechanism must be prominent and easy to find. Per CSAM.md Part 1C Step 7."}
        make new reminder with properties {name:"🟡 Apply for IWF membership (UK hash list)", due date:date "June 28, 2026", body:"Internet Watch Foundation (UK). Maintains separate hash list of known CSAM. Important for UK Online Safety Act compliance. Per CSAM.md Part 2A."}
        make new reminder with properties {name:"🔴 Implement age verification system for R/X content", due date:date "June 28, 2026", body:"Not just \"click yes I'm 18.\" Credit card verification, government ID, or third-party age verification service. Default: all content G-rated. PG/PG-13 requires 13+. R/X requires 18+ AND explicit opt-in. Per feedback_content_enforcement_policy."}
        make new reminder with properties {name:"🔴 Build AI image content classification pipeline for xamlr.com", due date:date "June 28, 2026", body:"Scans ALL uploaded images before publication. Classifies: nudity levels, kink indicators, fetish content, BDSM imagery, explicit content. Misclassified content → entire blog invisible. Appeals within 24 hours. Per feedback_content_enforcement_policy."}
        make new reminder with properties {name:"🔴 Designate 2257 Custodian of Records", due date:date "June 28, 2026", body:"Required for any platform hosting sexually explicit UGC. Maintain records: legal name + DOB of all performers, picture ID copies, cross-reference index. Records maintained 5 years after content last published. Available for AG inspection. Per CSAM.md Part 1C."}
        make new reminder with properties {name:"🔴 Obtain OneList API credentials + base URL", due date:date "April 11, 2026", body:"Required for data migration and all cross-product integration. Confirm custom metadata fields (JSONB), needed link types, namespace scoping. Test bulk import endpoint capacity and rate limits. Per ONELIST_MIGRATION_PLAN Phase 0 and BRYAN_TASK_LIST."}
        make new reminder with properties {name:"🟡 Execute OneList data migration — entries, relationships, chats", due date:date "May 2, 2026", body:"Phase 1: 7,914 entries. Phase 2: 7,208 relationships. Phase 3: 345,294 chat messages. Phase 4: 88 conversations. Phase 5: 2,455 reviews. Build UID→OneList UUID mapping. Verify counts match. Per ONELIST_MIGRATION_PLAN."}
        make new reminder with properties {name:"🟢 Create ChatGPT GPT for TrueAssess in GPT Store", due date:date "June 7, 2026", body:"\"TrueAssess Self-Assessment Guide\" — connects to trueassess.me knowledge base. Users interact with assessment framework in ChatGPT. Discovery channel within ChatGPT ecosystem. Per SEARCH_AI_INDEXING_PLAN Section 2.1."}
        make new reminder with properties {name:"🟢 Register ChatGPT plugin/action for trueassess.me API", due date:date "June 7, 2026", body:"Register OpenAI plugin allowing ChatGPT to call trueassess.me API. Users take assessments in ChatGPT. Requires OpenAPI spec. Submit via platform.openai.com. Per SEARCH_AI_INDEXING_PLAN."}
        make new reminder with properties {name:"🟢 Set up RSS feeds for all domains", due date:date "May 16, 2026", body:"RSS enables automated distribution and AI/search engine discovery. Per SEARCH_AI_INDEXING_PLAN Section 8."}
        make new reminder with properties {name:"🟢 Register with Brave Search webmaster tools", due date:date "April 11, 2026", body:"Independent web index. Privacy-conscious, tech-savvy audience. Register all 4 domains. search.brave.com/webmaster. Per SEARCH_AI_INDEXING_PLAN Section 1.9."}
        make new reminder with properties {name:"🟡 Conduct quarterly self-OSINT audit", due date:date "June 22, 2026", body:"Search for name, usernames, email, phone, address across search engines, social media, data broker sites, public records, reverse image search, domain WHOIS. Per PERSONAL_SECURITY_PLAN Level 2."}
        make new reminder with properties {name:"🟡 Review personal security plan quarterly", due date:date "June 22, 2026", body:"Review and update security posture based on current threat level. Adjust measures up or down. Per PERSONAL_SECURITY_PLAN review schedule."}
        make new reminder with properties {name:"🟡 Set up SSO (SAML/OIDC) via WorkOS or Auth0", due date:date "June 27, 2026", body:"Non-negotiable for enterprise buyers. WorkOS $49/mo for 25 SSO connections. Required for business tier ($29/seat/month). Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
        make new reminder with properties {name:"🟡 Build admin dashboard for team/organization accounts", due date:date "June 27, 2026", body:"Admin creates team, invites by email, sets assessment tier, views group compatibility. Assessment completion rates, conflict risk flags, recommended interventions. Monthly PDF/CSV export. Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
        make new reminder with properties {name:"🟡 Prepare data processing agreements (DPAs) for GDPR", due date:date "June 21, 2026", body:"Documentation stating where data is stored (US/EU), how data is processed. Required for enterprise customers. Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
        make new reminder with properties {name:"🟢 Set up UptimeRobot for availability monitoring", due date:date "May 2, 2026", body:"Free tier monitors all domain endpoints. Alerts on downtime. Part of monitoring stack. Per ASTEROID_LAUNCH_STRATEGY infrastructure checklist."}
        make new reminder with properties {name:"🔴 Provision API origin infrastructure (Fly.io or AWS ECS)", due date:date "May 2, 2026", body:"Dynamic endpoints for assessment engine, coaching, search, auth. Separate from static CDN layer. Per ASTEROID_LAUNCH_STRATEGY and CDN_INFRASTRUCTURE_PLAN."}
        make new reminder with properties {name:"🔴 Provision PostgreSQL database (Neon, Supabase, or RDS)", due date:date "May 2, 2026", body:"Primary data store for user accounts, assessment results, compatibility analyses. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Provision Redis for caching, job queues, rate limiting", due date:date "May 2, 2026", body:"Required for conversation import job processing, pattern detection background jobs, rate limiting bot requests. Per ASTEROID_LAUNCH_STRATEGY and CDN_INFRASTRUCTURE_PLAN."}
        make new reminder with properties {name:"🟡 Deploy Meilisearch for full-text search", due date:date "May 16, 2026", body:"Open-source, handles 10K+ documents. Self-hosted on API origin. Powers search across all content on all domains. Per CDN_INFRASTRUCTURE_PLAN."}
        make new reminder with properties {name:"🔴 Set up automated deployment pipeline", due date:date "May 2, 2026", body:"Push to main → build → deploy to Cloudflare Pages (static) + API origin (dynamic). Atomic deploys, instant rollback. Per ASTEROID_LAUNCH_STRATEGY infrastructure checklist."}
        make new reminder with properties {name:"🔴 Configure DKIM, SPF, DMARC records for email deliverability", due date:date "April 4, 2026", body:"Required for ConvertKit emails to not go to spam. Test with mail-tester.com, target 9+/10 score. Per WEEK_MINUS_8_BUZZ_PLAN Section 2.3."}
        make new reminder with properties {name:"🟢 Set up affiliate tracking system", due date:date "May 16, 2026", body:"Deploy Rewardful, FirstPromoter, or custom. Track influencer referrals. Per ASTEROID_LAUNCH_STRATEGY accounts checklist."}
        make new reminder with properties {name:"🟡 Build result card generator for social sharing", due date:date "May 16, 2026", body:"Shareable images for Instagram Stories (9:16), TikTok, Twitter. Each assessment result gets a beautiful card. \"Challenge a friend\" button. Per ASTEROID_LAUNCH_STRATEGY content checklist."}
        make new reminder with properties {name:"🟢 Set up cryptocurrency payment fallback (BTCPay Server)", due date:date "June 28, 2026", body:"Censorship-resistant payment for religious content platform. Self-hosted BTCPay Server or Coinbase Commerce. Stablecoins (USDC/USDT) reduce volatility. Even 2-5% of users paying crypto ensures revenue continuity if traditional processors terminate. Per PRIVACY_ANONYMITY_PLAN Section 3.2."}
        make new reminder with properties {name:"🟢 Announce open data program for researchers", due date:date "July 12, 2026", body:"Any researcher can access anonymized aggregate assessment data for free. Condition: cite trueassess.me. Generates academic citations within 12-18 months — .edu backlinks and credibility. Per ASTEROID_LAUNCH_STRATEGY Section 1.3."}
        make new reminder with properties {name:"🟢 Announce crowdfunded research pipeline", due date:date "July 12, 2026", body:"1% of subscription revenue to research fund. Premium subscribers vote on which studies to fund. Generates studies, studies generate credibility, credibility generates users. Flywheel. Per ASTEROID_LAUNCH_STRATEGY Section 1.3."}
        make new reminder with properties {name:"🟢 Set up dark web / social media threat monitoring", due date:date "October 2026", body:"Services like ZeroFox or Brandwatch. Monitor for threats, doxxing attempts, coordinated harassment. Start at Phase 3 (viral moment / media attention). $500-2,000/month. Per PERSONAL_SECURITY_PLAN Level 4."}
        make new reminder with properties {name:"🟡 Build \"Import your 16Personalities result\" migration feature", due date:date "June 27, 2026", body:"User enters 4-letter type, sees what 16Personalities told them vs what it missed vs the beliefs underneath. Competitor migration lever. Per ASTEROID_LAUNCH_STRATEGY Section 1.2."}
        make new reminder with properties {name:"🟢 Build \"Compare your CliftonStrengths\" migration feature", due date:date "June 27, 2026", body:"User enters top 5 strengths, sees additional dimensions CliftonStrengths ignores. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟡 Set up Grafana or Datadog for infrastructure metrics", due date:date "May 16, 2026", body:"Server response times, error rates, database connections, API latency. War room monitoring on D-Day. Per ASTEROID_LAUNCH_STRATEGY."}
        make new reminder with properties {name:"🟢 ATS/HRIS integration (Greenhouse, Lever, BambooHR) — 90 days post-launch", due date:date "October 10, 2026", body:"30 days per integration. Webhook APIs. Nice-to-have for enterprise adoption. Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
        make new reminder with properties {name:"🟢 White-label option for therapists/coaches ($50/mo)", due date:date "October 10, 2026", body:"Therapist embeds assessments on own website with their branding. 1,000 therapist accounts in year one, each a distribution point. Per ASTEROID_LAUNCH_STRATEGY Section 1.4."}
    end tell
end tell