tell application "Calendar"
    set mirrorCal to calendar "Mirror"
    make new event at end of events of mirrorCal with properties {summary:"LLC Formation + Business Infrastructure Setup", start date:date "March 22-28, 2026 at 9:00:00 AM", end date:date "March 22-28, 2026 at 10:00:00 AM", description:"Week 1 critical path: form LLC, get EIN, open bank account, buy domains, set up security infrastructure (YubiKeys, VPN, password manager, business email, PO Box). These block everything downstream."}
    make new event at end of events of mirrorCal with properties {summary:"Content Pre-Seeding Begins (Week -14)", start date:date "March 22, 2026 at 9:00:00 AM", end date:date "March 22, 2026 at 10:00:00 AM", description:"Google needs 4-8 weeks to index and rank new content. Foundation content must be live 6 weeks before announcement so organic traffic is flowing by Week -8."}
    make new event at end of events of mirrorCal with properties {summary:"Teaser Landing Page Goes Live", start date:date "April 19, 2026 at 9:00:00 AM", end date:date "April 19, 2026 at 10:00:00 AM", description:"trueassess.me waitlist page and all satellite \"coming soon\" pages go live. Email capture begins. Not yet announced publicly."}
    make new event at end of events of mirrorCal with properties {summary:"Mirror Bot Goes Live on Social Media", start date:date "May 3, 2026 at 9:00:00 AM", end date:date "May 3, 2026 at 10:00:00 AM", description:"Mirror AI personality begins operating on X, Bluesky, and Discord. LLM API costs increase. Bot building audience for 2 weeks before announcement."}
    make new event at end of events of mirrorCal with properties {summary:"ANNOUNCEMENT DAY — trueassess.me Revealed + Founding Member Sales Open", start date:date "May 17, 2026 at 9:00:00 AM", end date:date "May 17, 2026 at 10:00:00 AM", description:"The commitment point. Once FM sales open, launch date is locked. Mirror bot announces trueassess.me. Founding Member sales ($39/yr, $299 lifetime, $499 all-access) begin. 1,000 total spots. This is the inflection point — everything before was flexible."}
    make new event at end of events of mirrorCal with properties {summary:"truemirror.me Teased", start date:date "May 31, 2026 at 9:00:00 AM", end date:date "May 31, 2026 at 10:00:00 AM", description:"Second reveal in the sequential launch. truemirror.me announced as AI relationship coaching platform. \"Included for Founding Members.\""}
    make new event at end of events of mirrorCal with properties {summary:"xamory.com + xamlr.com Teased", start date:date "June 14, 2026 at 9:00:00 AM", end date:date "June 14, 2026 at 10:00:00 AM", description:"Fourth reveal. Dating platform + blogging platform revealed as interconnected ecosystem."}
    make new event at end of events of mirrorCal with properties {summary:"levnation.com + levciti.com Teased", start date:date "June 28, 2026 at 9:00:00 AM", end date:date "June 28, 2026 at 10:00:00 AM", description:"Sixth reveal. Civic engagement layer shown. Full ecosystem scope now visible. \"[X] Founding Member spots remaining.\""}
    make new event at end of events of mirrorCal with properties {summary:"levlife.co Teased — Final Reveal", start date:date "July 5, 2026 at 9:00:00 AM", end date:date "July 5, 2026 at 10:00:00 AM", description:"Complete ecosystem picture revealed. Final Founding Member push. Launch is one week away."}
    make new event at end of events of mirrorCal with properties {summary:"D-DAY — EVERYTHING LAUNCHES", start date:date "July 12, 2026 at 9:00:00 AM", end date:date "July 12, 2026 at 10:00:00 AM", description:"All five properties go live simultaneously. DNS cutover at midnight ET. Systems check at 05:00 ET. Press embargo lifts at 06:00 ET. Product Hunt launches at 07:00 ET. HN post at 08:00 ET. Social blitz at 09:00 ET. Email blast at 10:00 ET. Influencer posts at 11:00 ET. Reddit at 12:00 ET. YouTube premieres at 13:00 ET."}
end tell