import json
from datetime import datetime, timezone

# Load existing
with open("/Users/user/personal/sb/trueassess/priv/data/content_backlog.json") as f:
    data = json.load(f)

tickets = data["tickets"]
existing_slugs = {t["slug"] for t in tickets}

def add(slug, title, typ, pipeline, priority, deps=None):
    if slug not in existing_slugs:
        tickets.append({
            "slug": slug,
            "title": title,
            "type": typ,
            "pipeline": pipeline,
            "priority": priority,
            "dependencies": deps or [],
            "status": "backlog"
        })
        existing_slugs.add(slug)

# ============================================================
# EXPAND: More belief decomposition pages (target: 945 total)
# ============================================================

# Parenting beliefs (expand to ~158)
parenting_beliefs = [
    "tiger-parenting-produces-success", "free-range-parenting", "co-sleeping-harmful",
    "breastfeeding-mandatory", "formula-feeding-acceptable", "cry-it-out-training",
    "positive-reinforcement-only", "natural-consequences-best-teacher",
    "children-should-have-chores", "allowance-teaches-money-skills",
    "children-should-choose-religion", "children-need-two-parents",
    "single-parents-disadvantage-children", "adopted-children-same-as-biological",
    "spanking-is-discipline", "spanking-is-abuse", "children-should-be-vaccinated",
    "public-school-superior", "private-school-superior", "unschooling-valid",
    "gender-neutral-parenting", "boys-need-male-role-models",
    "children-should-play-sports", "video-games-harm-children",
    "social-media-harms-teens", "teenagers-need-privacy",
    "parents-should-be-friends", "helicopter-parenting-necessary",
    "snowplow-parenting-harmful", "free-play-essential",
    "structured-activities-better", "nature-deficit-real",
    "children-need-religion", "children-need-adversity",
    "participation-trophies-fine", "competitive-sports-build-character",
    "children-should-earn-privileges", "unconditional-love-enables-bad-behavior",
    "children-mirror-parents", "birth-order-affects-personality",
    "only-children-spoiled", "large-families-better", "small-families-better",
    "working-mothers-harm-children", "stay-at-home-moms-more-valuable",
    "daycare-harmful", "daycare-beneficial-socialization",
    "co-parenting-after-divorce-possible", "parental-alienation-real",
    "children-resilient-to-divorce", "divorce-always-harms-children",
    "stepparents-can-love-like-biological", "blended-families-harder",
    "grandparents-should-not-interfere", "grandparents-essential",
    "parents-responsible-for-adult-children", "18-and-done-parenting",
    "children-owe-parents-respect", "respect-must-be-earned-by-parents",
    "parents-should-apologize-to-children", "parental-authority-absolute",
    "children-should-call-parents-by-name", "family-meals-essential",
    "screen-time-limits-necessary", "technology-literacy-more-important",
    "children-should-learn-multiple-languages", "bilingual-parenting-confuses",
    "gifted-children-need-special-education", "all-children-are-gifted",
    "adhd-is-overdiagnosed-in-children", "medication-for-children-justified",
    "therapy-for-children-necessary", "children-should-work-it-out",
    "bullying-builds-character", "zero-tolerance-bullying-policies",
    "children-should-fight-back", "turn-other-cheek-teaching",
    "religious-education-essential", "secular-education-sufficient",
    "sex-education-parental-duty", "abstinence-only-education",
    "comprehensive-sex-education", "children-should-learn-consent-early",
    "childhood-innocence-must-be-protected", "sheltering-backfires",
    "children-should-know-about-money", "childhood-should-be-carefree",
    "chores-build-responsibility", "childhood-labor-exploitation",
    "allowance-tied-to-chores", "unconditional-allowance",
    "children-should-save-money", "generosity-taught-young",
    "materialism-harms-children", "providing-abundantly-shows-love",
    "children-need-routine", "flexibility-teaches-adaptability",
    "bedtime-routines-essential", "letting-children-self-regulate-sleep",
    "family-traditions-essential", "every-family-different",
    "cultural-traditions-must-be-passed", "children-choose-own-culture",
    "manners-essential", "manners-are-classist", "respect-for-authority-essential",
    "questioning-authority-healthy", "obedience-vs-compliance",
    "empathy-can-be-taught", "empathy-is-innate", "resilience-can-be-built",
    "children-naturally-resilient", "attachment-parenting-clingy",
    "secure-attachment-foundation", "permissive-parenting-harmful",
    "authoritarian-parenting-harmful", "neglectful-parenting-most-harmful",
    "parenting-style-determines-outcome", "genetics-more-important-than-parenting",
    "peer-influence-overrides-parents", "parents-primary-influence",
    "parenting-books-helpful", "instinct-better-than-books",
    "perfect-parenting-impossible", "good-enough-parenting-sufficient",
    "parenting-hardest-job", "parenting-most-rewarding-job",
    "regretful-parents-exist", "choosing-not-to-parent-valid",
    "pronatalism-harmful", "antinatalism-valid",
    "adoption-better-than-biological", "biological-connection-matters",
    "donor-conceived-children-right-to-know", "surrogacy-ethical",
    "ivf-playing-god", "reproductive-technology-gift",
]

relationship_beliefs = [
    "communication-most-important", "trust-most-important", "respect-most-important",
    "love-fades-with-time", "love-deepens-with-time", "passion-cannot-last",
    "passion-can-be-maintained", "marriage-is-commitment", "marriage-is-outdated",
    "cohabitation-before-marriage-wise", "cohabitation-increases-divorce",
    "prenups-unromantic", "prenups-practical", "divorce-sometimes-best-option",
    "divorce-always-failure", "staying-together-for-kids-right",
    "staying-together-for-kids-wrong", "affairs-unforgivable",
    "affairs-forgivable", "emotional-affairs-worse-than-physical",
    "physical-affairs-worse-than-emotional", "monogamy-natural",
    "monogamy-unnatural", "polyamory-valid", "polyamory-avoidance",
    "open-relationships-work", "open-relationships-doomed",
    "relationship-needs-spark", "spark-is-myth", "chemistry-essential",
    "chemistry-overrated", "friendship-foundation-of-love",
    "romantic-love-different-from-friendship", "love-is-choice-not-feeling",
    "love-is-feeling-not-choice", "you-shouldnt-have-to-try",
    "effort-shows-love", "if-they-wanted-to-they-would",
    "relationships-require-sacrifice", "sacrifice-is-codependency",
    "fighting-means-unhealthy", "fighting-means-passionate",
    "never-fight-in-front-of-children", "modeling-repair-good-for-children",
    "your-partner-should-be-your-best-friend", "partners-need-separate-friends",
    "couples-should-share-everything", "privacy-in-relationships-healthy",
    "phone-checking-justified", "phone-checking-violation",
    "social-media-ruins-relationships", "social-media-can-strengthen",
    "long-distance-never-works", "long-distance-can-work",
    "age-gap-relationships-wrong", "age-gap-relationships-fine",
    "rebound-relationships-unhealthy", "rebound-relationships-can-work",
    "dating-apps-superficial", "dating-apps-necessary-modern-tool",
    "marriage-counseling-last-resort", "marriage-counseling-preventive",
    "therapist-should-be-couples", "individual-therapy-first",
    "forgiveness-required-for-healing", "forgiveness-not-always-necessary",
    "boundaries-in-relationships-essential", "too-many-boundaries-harmful",
    "vulnerability-is-strength", "vulnerability-is-weakness",
    "men-should-initiate", "anyone-can-initiate",
    "women-want-providers", "women-want-partners",
    "men-need-respect-more-than-love", "everyone-needs-both",
    "codependency-always-bad", "interdependence-vs-independence",
    "independence-in-relationships-essential", "too-much-independence-avoidance",
    "attachment-style-determines-compatibility", "attachment-styles-can-change",
    "narcissists-cannot-change", "everyone-can-change", "some-people-cannot-change",
    "red-flags-should-end-relationship", "everyone-has-red-flags",
    "green-flags-more-important-than-red", "deal-breakers-are-absolute",
    "unconditional-love-exists-in-romance", "all-love-is-conditional",
    "love-language-mismatch-fatal", "love-languages-can-be-learned",
    "sexual-compatibility-essential", "sexual-compatibility-built",
    "frequency-of-sex-indicates-health", "quality-over-quantity",
    "emotional-intimacy-more-important", "physical-intimacy-equally-important",
    "couples-should-have-same-values", "different-values-can-complement",
    "religion-must-match", "mixed-faith-marriages-work",
    "in-laws-make-or-break", "in-law-boundaries-essential",
    "your-family-comes-first", "your-partner-comes-first",
    "children-change-everything", "children-strengthen-relationships",
    "children-stress-relationships", "childless-by-choice-valid",
    "every-relationship-has-seasons", "relationship-should-always-feel-good",
]

gender_beliefs = [
    "traditional-masculinity-good", "traditional-masculinity-toxic",
    "feminism-equality-movement", "feminism-anti-men", "third-wave-feminism-valid",
    "fourth-wave-feminism-excessive", "manosphere-has-valid-points",
    "manosphere-is-radicalization", "red-pill-contains-truth",
    "red-pill-is-misogyny", "mgtow-rational-response", "mgtow-is-retreat",
    "men-disposable-in-society", "male-privilege-real",
    "female-privilege-exists", "intersectionality-valid-framework",
    "gender-pay-gap-real", "gender-pay-gap-choices",
    "women-in-stem-important", "meritocracy-should-decide",
    "affirmative-action-necessary", "affirmative-action-discrimination",
    "chivalry-respectful", "chivalry-patronizing", "chivalry-dead",
    "men-should-pay-for-dates", "splitting-bills-equal",
    "women-should-be-courted", "courting-is-performative",
    "gender-differences-biological", "gender-differences-socialized",
    "gender-binary-valid", "non-binary-valid-identity",
    "trans-women-are-women", "sex-and-gender-different",
    "masculinity-crisis-real", "masculinity-evolving-naturally",
    "boys-crisis-in-education", "girls-still-disadvantaged",
    "body-positivity-healthy", "body-positivity-enables-unhealthiness",
    "beauty-standards-oppressive", "beauty-standards-biological",
    "modesty-respectful", "modesty-policing-control",
    "sexual-liberation-good", "sexual-liberation-harmful",
    "hookup-culture-damaging", "hookup-culture-freedom",
    "monogamy-patriarchal", "monogamy-natural-preference",
    "domestic-labor-gendered", "domestic-labor-negotiated",
    "breadwinner-stress-valid", "breadwinning-privilege",
    "stay-at-home-dads-valid", "stay-at-home-dads-emasculated",
    "maternal-instinct-real", "paternal-instinct-real",
    "custody-bias-against-fathers", "custody-courts-fair",
    "alimony-fair", "alimony-outdated", "child-support-fair",
]

politics_beliefs = [
    "trickle-down-economics-works", "trickle-down-myth",
    "minimum-wage-should-increase", "minimum-wage-kills-jobs",
    "universal-healthcare-right", "private-healthcare-better",
    "student-debt-should-be-forgiven", "student-debt-personal-responsibility",
    "college-necessary", "college-overpriced-scam", "trade-schools-undervalued",
    "military-spending-excessive", "military-spending-necessary",
    "police-should-be-defunded", "police-need-more-funding",
    "drug-war-failed", "drug-legalization-harmful",
    "marijuana-should-be-legal", "marijuana-gateway-drug",
    "psychedelics-should-be-legal", "psychedelics-dangerous",
    "death-penalty-deterrent", "death-penalty-barbaric",
    "two-party-system-broken", "two-party-system-stable",
    "electoral-college-fair", "electoral-college-outdated",
    "gerrymandering-rigging", "redistricting-normal",
    "voter-id-reasonable", "voter-id-suppression",
    "mail-in-voting-safe", "mail-in-voting-risky",
    "term-limits-needed", "experience-in-office-valuable",
    "lobbying-corruption", "lobbying-free-speech",
    "citizens-united-disastrous", "corporate-speech-protected",
    "social-security-going-bankrupt", "social-security-fixable",
    "medicare-for-all-best", "public-option-compromise",
    "welfare-creates-dependency", "welfare-safety-net",
    "food-stamps-abused", "food-stamps-essential",
    "border-wall-effective", "border-wall-waste",
    "path-to-citizenship-fair", "amnesty-unfair",
    "refugees-welcome", "refugee-limits-necessary",
    "nationalism-healthy", "nationalism-dangerous",
    "globalization-good", "globalization-hurts-workers",
    "foreign-aid-waste", "foreign-aid-investment",
    "nato-essential", "nato-outdated",
    "united-nations-valuable", "united-nations-ineffective",
    "climate-change-existential", "climate-change-exaggerated",
    "nuclear-energy-necessary", "nuclear-energy-too-risky",
    "renewable-energy-sufficient", "renewable-energy-unreliable",
    "carbon-tax-effective", "carbon-tax-punishes-poor",
    "electric-vehicles-future", "electric-vehicles-overhyped",
    "crypto-future-of-money", "crypto-speculation-bubble",
    "regulation-protects-people", "regulation-stifles-innovation",
    "big-tech-needs-regulation", "free-market-regulates-tech",
    "section-230-should-be-repealed", "section-230-protects-speech",
    "censorship-never-justified", "hate-speech-should-be-banned",
    "second-amendment-absolute", "second-amendment-needs-limits",
    "assault-weapons-ban-effective", "assault-weapons-ban-ineffective",
    "reparations-justified", "reparations-impractical",
    "critical-race-theory-valuable", "critical-race-theory-harmful",
    "white-privilege-real", "white-privilege-myth",
    "affirmative-action-still-needed", "affirmative-action-reverse-discrimination",
    "defund-means-reallocate", "defund-means-abolish",
    "prison-reform-needed", "tough-on-crime-works",
    "restorative-justice-effective", "restorative-justice-soft",
    "homelessness-housing-problem", "homelessness-mental-health-problem",
    "universal-basic-income-viable", "ubi-destroys-work-ethic",
    "automation-will-eliminate-jobs", "automation-creates-new-jobs",
    "unions-necessary", "unions-outdated",
    "right-to-work-freedom", "right-to-work-anti-union",
    "gig-economy-exploitation", "gig-economy-flexibility",
]

religion_beliefs = [
    "god-exists", "god-does-not-exist", "agnosticism-most-honest",
    "multiple-gods-exist", "god-is-impersonal", "god-is-personal",
    "afterlife-is-real", "afterlife-is-wishful-thinking",
    "hell-exists-literal", "hell-is-metaphor", "universalism-all-saved",
    "annihilationism-better", "reincarnation-real", "one-life-only",
    "prayer-changes-outcomes", "prayer-changes-the-pray-er",
    "miracles-happen", "miracles-dont-happen", "miracles-stopped",
    "bible-inerrant", "bible-inspired-not-literal", "bible-human-document",
    "quran-inerrant", "quran-historically-contextual",
    "church-attendance-necessary", "spiritual-practice-sufficient",
    "tithing-commanded", "tithing-cultural", "tithing-manipulation",
    "evolution-compatible-with-faith", "evolution-contradicts-faith",
    "young-earth-creationism", "old-earth-creationism",
    "original-sin-real", "original-sin-myth", "total-depravity-accurate",
    "humans-basically-good", "humans-basically-selfish",
    "satan-is-real", "satan-is-metaphor", "spiritual-warfare-real",
    "demons-are-real", "demon-possession-mental-illness",
    "speaking-in-tongues-real", "speaking-in-tongues-social-behavior",
    "prosperity-gospel-true", "prosperity-gospel-heresy",
    "faith-healing-real", "faith-healing-dangerous",
    "religious-experience-valid-evidence", "religious-experience-neurological",
    "mystical-experiences-proof-of-god", "mystical-experiences-brain-states",
    "meditation-connects-to-god", "meditation-just-relaxation",
    "yoga-is-hindu-worship", "yoga-is-exercise",
    "astrology-has-basis", "astrology-is-pseudoscience",
    "tarot-has-insight", "tarot-is-random",
    "manifest-destiny-real", "prosperity-through-positive-thinking",
    "law-of-attraction-works", "law-of-attraction-magical-thinking",
    "religious-freedom-absolute", "religious-freedom-has-limits",
    "secular-government-best", "christian-nation-valid",
    "separation-of-church-and-state", "religion-should-guide-law",
    "moral-relativism-dangerous", "moral-absolutism-dangerous",
    "natural-law-real", "natural-law-construct",
    "ten-commandments-universal", "ten-commandments-culturally-specific",
    "golden-rule-universal", "golden-rule-insufficient",
    "suffering-has-purpose", "suffering-meaningless",
    "suffering-punishment", "suffering-growth-opportunity",
    "evil-proves-no-god", "evil-free-will-defense",
    "science-disproves-religion", "science-and-religion-different-domains",
    "religious-trauma-real", "religious-trauma-exaggerated",
    "children-should-choose-religion", "children-should-be-raised-in-faith",
    "deconstruction-healthy", "deconstruction-deception",
]

health_beliefs = [
    "therapy-for-everyone", "therapy-only-for-serious-problems",
    "medication-first-line", "therapy-first-then-medication",
    "ssris-effective", "ssris-overprescribed", "ssris-band-aid",
    "anxiety-chemical-imbalance", "anxiety-response-to-environment",
    "depression-genetic", "depression-environmental", "depression-choice",
    "exercise-as-good-as-medication", "exercise-necessary-supplement",
    "meditation-scientifically-proven", "meditation-overhyped",
    "yoga-therapeutic", "yoga-just-stretching",
    "organic-food-healthier", "organic-food-marketing",
    "gmo-foods-safe", "gmo-foods-risky", "gluten-free-healthier",
    "gluten-sensitivity-real", "celiac-vs-gluten-sensitivity",
    "veganism-healthiest", "meat-necessary-for-health",
    "keto-diet-effective", "keto-diet-unsustainable",
    "intermittent-fasting-beneficial", "eating-regularly-better",
    "bmi-valid-measure", "bmi-outdated", "weight-determines-health",
    "health-at-every-size-valid", "obesity-always-unhealthy",
    "fat-shaming-motivation", "fat-shaming-harmful",
    "body-positivity-helpful", "body-neutrality-better",
    "cosmetic-surgery-empowering", "cosmetic-surgery-symptom",
    "smoking-worst-health-behavior", "alcohol-worse-than-smoking",
    "moderate-drinking-ok", "no-safe-level-of-alcohol",
    "marijuana-harmless", "marijuana-has-risks",
    "psychedelics-therapeutic", "psychedelics-dangerous",
    "chronic-pain-psychosomatic", "chronic-pain-real",
    "fibromyalgia-real", "fibromyalgia-contested",
    "long-covid-real", "long-covid-psychosomatic",
    "chronic-fatigue-real", "chronic-fatigue-laziness",
    "autoimmune-conditions-increasing", "autoimmune-better-diagnosed",
    "gut-health-determines-mental-health", "gut-brain-connection-overhyped",
    "sleep-most-important-health-factor", "exercise-most-important",
    "stress-kills", "stress-can-be-beneficial",
    "burnout-real-medical-condition", "burnout-excuse",
    "screen-time-harmful-to-health", "screen-time-neutral",
    "emf-radiation-harmful", "emf-safe", "5g-conspiracy",
    "fluoride-harmful", "fluoride-safe",
    "anti-aging-possible", "aging-inevitable",
    "supplements-necessary", "supplements-expensive-urine",
    "probiotics-effective", "probiotics-marketing",
    "chiropratic-effective", "chiropractic-pseudoscience",
    "acupuncture-works", "acupuncture-placebo",
    "naturopathy-valid", "naturopathy-dangerous",
    "homeopathy-works", "homeopathy-debunked",
    "essential-oils-therapeutic", "essential-oils-nice-smell-only",
]

# Add all expanded beliefs
for domain_name, belief_list in [
    ("parenting", parenting_beliefs),
    ("relationships", relationship_beliefs),
    ("gender", gender_beliefs),
    ("politics", politics_beliefs),
    ("religion", religion_beliefs),
    ("health", health_beliefs),
]:
    for belief_slug in belief_list:
        add(f"belief-{domain_name}-{belief_slug}", f"Belief: {belief_slug.replace('-', ' ').title()} ({domain_name})", "belief", "trueassess_content", "p2", [])

# ============================================================
# More "Am I..." pages
# ============================================================
more_am_i = [
    ("am-i-asexual", "Am I Asexual?"),
    ("am-i-aromantic", "Am I Aromantic?"),
    ("am-i-polyamorous", "Am I Polyamorous?"),
    ("am-i-demisexual", "Am I Demisexual?"),
    ("am-i-sapiosexual", "Am I Sapiosexual?"),
    ("am-i-in-abusive-relationship", "Am I in an Abusive Relationship?"),
    ("am-i-enabler", "Am I an Enabler?"),
    ("am-i-emotional-eater", "Am I an Emotional Eater?"),
    ("am-i-alcoholic", "Am I an Alcoholic?"),
    ("am-i-addicted", "Am I Addicted?"),
    ("am-i-workaholic", "Am I a Workaholic?"),
    ("am-i-ocd", "Do I Have OCD?"),
    ("am-i-ptsd", "Do I Have PTSD?"),
    ("am-i-alexithymic", "Am I Alexithymic?"),
    ("am-i-sociopath", "Am I a Sociopath?"),
    ("am-i-psychopath", "Am I a Psychopath?"),
    ("am-i-dissociating", "Am I Dissociating?"),
    ("am-i-parentified", "Was I Parentified?"),
    ("am-i-enmeshed", "Am I in an Enmeshed Family?"),
    ("am-i-scapegoat", "Am I the Family Scapegoat?"),
]
for a_id, a_name in more_am_i:
    add(a_id, f"{a_name} -- Self-Assessment Landing Page", "landing", "trueassess_content", "p2", [])

# ============================================================
# More comparison pages
# ============================================================
more_comparisons = [
    ("attachment-anxious-vs-avoidant", "Anxious vs Avoidant Attachment"),
    ("narcissist-vs-borderline", "Narcissist vs Borderline"),
    ("codependency-vs-people-pleasing", "Codependency vs People-Pleasing"),
    ("ptsd-vs-cptsd", "PTSD vs C-PTSD"),
    ("bipolar-vs-bpd", "Bipolar vs BPD"),
    ("adhd-vs-anxiety", "ADHD vs Anxiety"),
    ("adhd-vs-autism", "ADHD vs Autism"),
    ("depression-vs-burnout", "Depression vs Burnout"),
    ("introvert-vs-avoidant", "Introvert vs Avoidant"),
    ("hsp-vs-autism", "HSP vs Autism"),
    ("empath-vs-codependent", "Empath vs Codependent"),
    ("ocd-vs-adhd", "OCD vs ADHD"),
    ("gaslighting-vs-misunderstanding", "Gaslighting vs Misunderstanding"),
    ("boundaries-vs-walls", "Boundaries vs Walls"),
    ("assertive-vs-aggressive", "Assertive vs Aggressive"),
    ("vulnerability-vs-oversharing", "Vulnerability vs Oversharing"),
    ("self-care-vs-selfishness", "Self-Care vs Selfishness"),
    ("healthy-anger-vs-rage", "Healthy Anger vs Rage"),
    ("grief-vs-depression", "Grief vs Depression"),
    ("loneliness-vs-aloneness", "Loneliness vs Aloneness"),
    ("love-vs-attachment", "Love vs Attachment"),
    ("compromise-vs-sacrifice", "Compromise vs Sacrifice"),
    ("forgiveness-vs-acceptance", "Forgiveness vs Acceptance"),
    ("accountability-vs-blame", "Accountability vs Blame"),
    ("influence-vs-manipulation", "Influence vs Manipulation"),
    ("confidence-vs-arrogance", "Confidence vs Arrogance"),
    ("empathy-vs-sympathy", "Empathy vs Sympathy"),
    ("guilt-vs-shame", "Guilt vs Shame"),
    ("fear-vs-anxiety", "Fear vs Anxiety"),
    ("trauma-response-vs-personality", "Trauma Response vs Personality"),
]
for c_id, c_name in more_comparisons:
    add(f"compare-{c_id}", f"{c_name} -- Comparison Page", "comparison", "trueassess_content", "p2", [])

# ============================================================
# More patterns from Bryan's 175 named patterns catalog
# ============================================================
more_patterns = [
    ("future-faking", "Future Faking"),
    ("breadcrumbing", "Breadcrumbing"),
    ("benching", "Benching"),
    ("orbiting", "Orbiting"),
    ("ghosting", "Ghosting"),
    ("zombie-ing", "Zombie-ing"),
    ("micro-cheating", "Micro-Cheating"),
    ("emotional-affair", "Emotional Affair Pattern"),
    ("trickle-truthing", "Trickle Truthing"),
    ("rug-sweeping", "Rug Sweeping"),
    ("rugsweeping-vs-forgiveness", "Rug Sweeping vs Genuine Forgiveness"),
    ("weaponized-therapy-language", "Weaponized Therapy Language"),
    ("spiritual-bypassing", "Spiritual Bypassing"),
    ("toxic-positivity", "Toxic Positivity"),
    ("bypassing-vulnerability", "Bypassing Vulnerability"),
    ("cheap-forgiveness", "Cheap Forgiveness"),
    ("pseudo-forgiveness", "Pseudo-Forgiveness"),
    ("conditional-forgiveness", "Conditional Forgiveness"),
    ("avoidant-forgiveness", "Avoidant Forgiveness"),
    ("premature-closure", "Premature Closure"),
    ("emotional-dumping", "Emotional Dumping"),
    ("venting-vs-processing", "Venting vs Processing"),
    ("retroactive-jealousy", "Retroactive Jealousy"),
    ("competitive-victimhood", "Competitive Victimhood"),
    ("pain-olympics", "Pain Olympics"),
    ("whataboutism", "Whataboutism in Relationships"),
    ("deflection", "Deflection"),
    ("intellectual-bullying", "Intellectual Bullying"),
    ("emotional-labor-imbalance", "Emotional Labor Imbalance"),
    ("mental-load", "Mental Load Pattern"),
    ("weaponized-helplessness", "Weaponized Helplessness"),
    ("parentifying-partner", "Parentifying Your Partner"),
    ("infantilizing-partner", "Infantilizing Your Partner"),
    ("testing-partner", "Testing Your Partner"),
    ("keeping-score-sex", "Keeping Score with Sex"),
    ("weaponizing-sex", "Weaponizing Sex"),
    ("withholding-affection", "Withholding Affection"),
    ("conditional-love-pattern", "Conditional Love Pattern"),
    ("hot-cold-pattern", "Hot-Cold Pattern"),
    ("push-pull-dynamic", "Push-Pull Dynamic"),
    ("drama-triangle", "Karpman Drama Triangle"),
    ("rescuer-pattern", "Rescuer Pattern"),
    ("persecutor-pattern", "Persecutor Pattern"),
    ("victim-pattern-drama", "Victim Pattern (Drama Triangle)"),
]
for p_id, p_name in more_patterns:
    add(f"pattern-{p_id}", f"{p_name} -- Pattern Encyclopedia Page", "pattern", "knowledge_web", "p2", [])

# ============================================================
# Rebuild summary
# ============================================================
by_type = {}
by_pipeline = {}
by_priority = {}
for t in tickets:
    by_type[t["type"]] = by_type.get(t["type"], 0) + 1
    by_pipeline[t["pipeline"]] = by_pipeline.get(t["pipeline"], 0) + 1
    by_priority[t["priority"]] = by_priority.get(t["priority"], 0) + 1

data["tickets"] = tickets
data["total_tickets"] = len(tickets)
data["generated_at"] = datetime.now(timezone.utc).isoformat()
data["summary"] = {
    "by_type": dict(sorted(by_type.items())),
    "by_pipeline": dict(sorted(by_pipeline.items())),
    "by_priority": dict(sorted(by_priority.items())),
}

with open("/Users/user/personal/sb/trueassess/priv/data/content_backlog.json", "w") as f:
    json.dump(data, f, indent=2)

print(f"Total tickets: {len(tickets)}")
print(f"\nBy type: {json.dumps(by_type, indent=2)}")
print(f"\nBy pipeline: {json.dumps(by_pipeline, indent=2)}")
print(f"\nBy priority: {json.dumps(by_priority, indent=2)}")
